service: golangservice
frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1

package:
  patterns:
    - '!./**'
    - ./bin/**
    - ./functions/**

functions:
  ${file(./functions/hello/_handlers.yml)}
